# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#MAIN PAGE - HOME
[[main]]
  name = "About Me"
  url = "aboutme/"
  weight = 10
  identifier = "home"

[[main]]
  name = "Overview"
  url = "aboutme/#overview"
  weight = 11
  parent = "home"

[[main]]
  name = "Skills"
  url = "aboutme/#skills"
  weight = 12
  parent = "home"

[[main]]
  name = "Awards and Honors"
  url = "aboutme/#awards-and-honors"
  weight = 13
  parent = "home"

#MAIN PAGE - WORK
[[main]]
  name = "My Work"
  url = "mywork/"
  weight = 20
  identifier = "mywork"

[[main]]
  name = "Experience"
  url = "mywork/#experience"
  weight = 21
  parent = "mywork"

[[main]]
  name = "Publications"
  url = "mywork/#publications"
  weight = 22
  parent = "mywork"

[[main]]
  name = "TA Experience"
  url = "mywork/#teaching"
  weight = 23
  parent = "mywork"

[[main]]
  name = "Talks"
  url = "mywork/#talks"
  weight = 24
  parent = "mywork"

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 30

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
